### PR TITLE
Add Font Awesome 5

### PR DESCRIPTION
**Pull request by jdorfman**
New structure. Instead of CSS they are now using .js

So we would have to do: `5.0.0/svg-with-js/js/fontawesome-all.js`

E.g.: this is their [Getting Started](https://fontawesome.com/get-started) code:
`<script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>`

### CODE REVIEW

**Comment by XhmikosR** [comment]
They still have the classic CSS way. Not sure how to proceed.

**Comment by jdorfman** [comment]
Me either

**Comment by XhmikosR** [comment]
They do have a CDN themselves now. Are you sure it makes sense to continue
providing Font Awesome?

Regardless, the proper way would be to provide both of their solutions.
Doable but needs some work.

On Dec 7, 2017 21:12, "Justin Dorfman" <notifications@github.com> wrote:

Me either

—
You are receiving this because your review was requested.

Reply to this email directly, view it on GitHub
<https://github.com/MaxCDN/bootstrap-cdn/pull/909#issuecomment-350065590>,
or mute the thread

**Comment by jdorfman** [comment]
Let's see how demand is. For now, just leave this open until further notice.

**Comment by jmervine** [comment]
We'll have to create special handling for `>=5`, something like we do here https://github.com/MaxCDN/bootstrap-cdn/blob/develop/tests/functional_test.js#L254, but in the `pug` file.

```pug
- if semver.gte(config.fontawesome[0].version, '5.0.0')
    // handle >=5
- else
    // current handling
```

For this to work, `semver` will have to be exported as a local to make it available in the views.

**Comment by jmervine** [comment]
On second thought, the above would need to be added to the new fontawesome legacy page in #913. The main page could just simply be updated to handle the new format.

**Comment by XhmikosR** [comment]
I'm still not sure if we should bother with Font Awesome since they do have their own CDN. In my opinion we should just move it to old and focus on the other stuff we have.

**Comment by jmervine** [comment]
I can get behind that. Perhaps just remove the primary FA page and header link, and remove the latest tag, so they all show up on `/legacy/fontawesome/`.

**Comment by jdorfman** [comment]
@jmervine thinking

**Comment by bukuh** [comment]
Please, consider to add fontawesome 5 CDN. It would be used by any websites powered by AMP (ampproject.org) because their CDN is not white-listed by AMP so I get an error (Not Valid AMP).

**Comment by jdorfman** [comment]
@bukuh what is the url that is being blocked?

**Comment by bukuh** [comment]
@jdorfman I mean, the URL (official CDN):
 
https://use.fontawesome.com/releases/v5.0.2/css/all.css" 

is blocked and not whitelisted by AMP.  So, I can't use it on AMP pages.

I love bootstrapcdn because it's whitelisted by AMP.

**Comment by jdorfman** [comment]
@bukuh got it. 

@jmervine @XhmikosR we got another request via Twitter: https://twitter.com/Devansh_Das/status/944909688281239552

Let's consider pushing this out next week following the same URI scheme as their CDN.

**Comment by jdorfman** [comment]
I would like to also promote Font Awesome 5 Pro on the FA slug. They have been great to us over the years and I want to return the favor.

**Comment by XhmikosR** [comment]
I don't agree at all personally. It's not a proper solution.

**Comment by jdorfman** [comment]
> I don't agree at all personally. It's not a proper solution.

@XhmikosR elaborate

**Comment by XhmikosR** [comment]
I meant about adding v5. They have changed the ways they offer the final
files. They now have a JS solution too. So this PR is at least incomplete.

If we agree to go forward with adding v5 we'd need to add both solutions.
Which would require many changes.

**Comment by jmervine** [comment]
I don’t see an issue only supporting th css option. If folks need the JS option they can got else where. That fits our patterns better. Perhaps we can consider supporting the JS option later, but for now....

**Comment by xAphex** [comment]
i tried to use their css only on my website, didnt work.
then i tried to use their cdn, and it worked.

**Comment by jdorfman** [comment]
**Pros:**
* Devs want it
* `*.bootstrapcdn.com` works with AMP (whitelisted)

**Cons:**
* The new URI scheme is long an complicated. Changing it breaks from our tradition of serving exactly how we get it
* We risk souring a relationship with the FA team

**Vote:** 
👍  = JS only 
🎉  = CSS only 
❤️  = Both
👎  = Link to FontAwesome.com until if/when they reach out.

**Comment by jmervine** [comment]
We've never supported legacy versions of FA, what's the reasoning behind starting now?

**Comment by jmervine** [comment]
I (reluctantly) voted both due to @xAphex's comments above. I'll grab this branch some time next week and start playing with it, unless someone else get's to it first.

**Comment by XhmikosR** [comment]
There's already a legacy font awesome page.

**Comment by jmervine** [comment]
HA! I totally missed that being added. Or simply forgot it was there. =P

**Comment by jdorfman** [comment]
@jmervine @XhmikosR I say we close this pull request and create an issue (linking to this PR) where we can send devs to discuss/vote. Once we hit a certain metric, we take action from there.

Thoughts?

**Comment by jmervine** [comment]
Leave for one more week. I'll try and take a pass at it.

**Comment by TechPandaIT** [comment]
As someone on the project's twitter said to me I should add my 2 cents, here they came:

Even tho FontAwesome has his own CDN, I think you should add it out of convenience. I of course just can speak for myself, but BootstrapCDN is a big part of my workflow whenever I need to work with Bootstrap, FontAwesome or even both.

**Comment by jdorfman** [comment]
@XhmikosR @jmervine got another request via Twitter. Let's start with `Version 5.0.12`

**Comment by XhmikosR** [comment]
@jdorfman: which files? v5 has all kind of crap...

**Comment by jdorfman** [comment]
@XhmikosR do we want to add `.js` as well? People seem to want it 

image

**Comment by XhmikosR** [comment]
Adding them on the CDN is the easy part. Showing every file available is something I personally don't agree with, but if someone suggests a way to do it, I could have a look.

**Comment by xAphex** [comment]
`.js` fixes problems with animated icons: https://fontawesome.com/how-to-use/web-fonts-with-css#animated-icons

the `.css` requires webfonts to work if you use it without CDN, that's why i switched to `.js`

just my 2 cents on the problem

**Comment by XhmikosR** [comment]
OK, I'm gonna add both flavors. I just need to figure out how the config will be and how to expose it in the frontend.

**Comment by lonix1** [comment]
Just support equivalent of 
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">`

Let's be practical - most devs are still using the css version of FA, and will continue to do so as it's the easiest option.

**Comment by jmervine** [comment]
I think it’s worth investigating how drag and drop supporting the existing css method is, and getting that in place. We can upload all files to the cdn but only surface the css variant in the UI. Adding a comment that the just files are present, “use at your own risk”, might be a good start.

**Comment by xAphex** [comment]
@lonix1 the link you included needs to be edited to include the v5.1.0 version of this [folder](https://github.com/MaxCDN/bootstrapcdn/tree/develop/cdn/font-awesome/4.7.0/fonts).

bootstrapcdn already did this in [v4.7.0](https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css).

`@font-face{font-family:'FontAwesome';src:url('../fonts/fontawesome-webfont.eot?v=4.7.0');src:url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'),url('../fonts/fontawesome-webfont.woff2?v=4.7.0') format('woff2'),url('../fonts/fontawesome-webfont.woff?v=4.7.0') format('woff'),url('../fonts/fontawesome-webfont.ttf?v=4.7.0') format('truetype'),url('../fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular') format('svg')`

**Comment by jdorfman** [comment]
Vote: should we close this issue?

y = 👍 
n = 👎

**Comment by Git-Harshit** [comment]
By the moment when I am writing this message, the font awesome does provide their _CSS_ using their own _CDN_. And, they are also willing to provide the personalized kits (with a unique kit code). But, in order to have it, every user needs to sign up on their website using their mail address before they can have a personal kit with a copy of the CSS. 

Though it may be preferred by those developers who are willing to go for a personalized and very carefully reserved version of font awesome, the process of obtaining it from their own CDN is a hassle for the developers who are just seeking a general version of FontAwesome and even beginners in getting started with a CDN directly. 

So, I would like to request you all to please consider obtaining a copy of latest _FontAwesome_ (v_5.13.0_ by this date) and share a direct link of the same, hosted at **Bootstrap CDN** for [FontAwesome](https://www.bootstrapcdn.com/fontawesome/).

**Comment by XhmikosR** [comment]
We are not going to add it. @jdorfman

**Comment by Git-Harshit** [comment]
But @XhimcosR, why not? I believe having a direct access to it from Bootstrap CDN would really be handy for many developers seeking a direct way to access it, without having to go through the long way of managing an account with FontAwesome's official website for CDN. 

Please consider about having it, though along with v4.7.0 already out in Bootstrap CDN. This shouldn't take much of a space.

**Comment by XhmikosR** [comment]
Because they already have a CDN. It's not a matter of space nor bandwidth.

@jdorfman should be able to shed more light.

**Comment by jdorfman** [comment]
> Because they already have a CDN. It's not a matter of space nor bandwidth.

@XhmikosR is correct. Also, I should have just made a decision in 2017 when he asked: "They do have a CDN themselves now. Are you sure it makes sense to continue providing Font Awesome?"

The decision should have been "**no**" because we are no longer "_The recommended CDN_" for Font Awesome.

@Git-Harshit I hear you and every developer that chimed in. The version of me 8 years ago would totally disapprove of the way I handled this issue in terms of time. 

This is not a code issue, this is me being a poor leader and trying to buy time to not be the bad guy.

The solution I recommend is using Font Awesome's CDN or jsDelivr for Font Awesome 5 (no email needed):  https://www.jsdelivr.com/package/npm/@fortawesome/fontawesome-free

**Pull request closed without merging**
