### PR TITLE
Add new versions

### PR DESCRIPTION
**Pull request by XhmikosR**
@jmervine please ping me when it's live

### CODE REVIEW

**Comment by XhmikosR** [comment]
Actually, let's wait a bit, we are going to have to release a v4.4.1 which I'm not sure it it affects Bootswatch or not yet. I need to check which Sass implementation they are using. Regardless, I'll push in this PR any further updates and ping you to upload the files.

**Comment by jdorfman** [comment]
@XhmikosR I would prefer it if you worked with @jmervine to upload (and everything else) so we are fully redundant. We shouldn't have to ping Josh if he is on holiday or is just not reachable.

**Comment by XhmikosR** [comment]
@jdorfman I can't know if and when someone is on vacation or not reachable. Also, there's just one too many things a person can do.

**Comment by jdorfman** [comment]
@XhmikosR true that. I will take this one and futures if needed. =)

**Pull request merged**
