### PR TITLE
Use img.shields.io for the GitHub Stars.

### PR DESCRIPTION
**Pull request by XhmikosR**
Checking if it's better or not.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I think it looks fine. Let me know what you guys think.

**Comment by jdorfman** [comment]
Doesn't show up on dev.bootstrapcdn.com

image

**Comment by XhmikosR** [comment]
Works for me here...

**Comment by jdorfman** [comment]
I'm unistalling Brave today.

**Comment by XhmikosR** [comment]
Maybe it considers it tracking.

**Comment by jdorfman** [comment]
They consider everything tracking https://community.brave.com/t/will-ethical-ads-that-fund-open-source-projects-be-supported-with-brave/44958

**Comment by jdorfman** [comment]
Actually @XhmikosR it's a Chromium issue. Works on FF but not Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by XhmikosR** [comment]
See #1276

**Pull request merged**
