### PR TITLE
Nuke Travis and use AppVeyor for both Linux and Windows tests.

### PR DESCRIPTION
**Pull request by XhmikosR**
I started this mostly as an experiment, but it seems it is faster, at least per-job. In total, it's about ~5-6 minutes but this includes both jobs. AppVeyor doesn't offer parallel builds in the free plan as far as I can tell.

Still, I find this more stable so far from my tests.

So, if we decide to go with this, here's the TODO:

- [x] Fix conditional caching
- [ ] Switch to the GitHub app for the AppVeyor repo integration
- [ ] Remove Travis from the repo hooks/required PR checks
- [ ] Add Joshua in the AppVeyor account

/CC @jmervine @jdorfman

### CODE REVIEW

**Comment by jdorfman** [comment]
If it's faster then fine with me 👍

**Comment by jmervine** [comment]
If it’s faster and supports testing on Linux, sure.

**Comment by XhmikosR** [comment]
Check https://ci.appveyor.com/project/jdorfman/bootstrapcdn/builds/19366002, both Ubuntu and Windows :)

**Comment by jmervine** [comment]
Looking good so far.

**Comment by XhmikosR** [comment]
Just yesterday Travis announce initial Windows support. I made a branch https://travis-ci.org/MaxCDN/bootstrapcdn/builds/440503011

It seems AppVeyor is faster...

**Pull request closed without merging**
