### PR TITLE
Move redirects to config

### LINKED ISSUE #1094: Move redirects to a json config file

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #1094 

Later, this will be used in routes too.

### CODE REVIEW

**Comment by jmervine** [comment]
This feels like an unnecessary layer of abstraction.

**Comment by jmervine** [comment]
Also, if you're going to abstract these, we should add a section to https://github.com/MaxCDN/bootstrapcdn/blob/develop/config/_config.yml

**Comment by XhmikosR** [comment]
I don't want to use _config.yml. It's already bloated with CDN stuff and www stuff shouldn't be there.

Like I said, the plan is to use this in routes too. And later add each page title and description to a config file too.

**Comment by XhmikosR** [comment]
I'll see how it'll look like in YAML. I just don't like having www and CDN stuff in one file because it has become pretty big.

**Comment by XhmikosR** [comment]
@jmervine: please check again.

**Comment by jmervine** [comment]
I personally like that better. I don’t disagree that _config.yml is getting a bit overloaded, but unless we’re going to throughly break them apart and load them in to a centralized config object, this works. 

I have strong opinions, weakly held, here. If you feel strongly about it being the other way, I’m down to discuss. Additionally if/when we break it out, I’m willing to consider using js over yaml, but I’d prefer to stay away from json.

**Comment by XhmikosR** [comment]
Nah, I don't mind currently but eventually we should break config.

So, this works for you?

**Pull request merged**
