### PR TITLE
Clean up `CONTENT_TYPE_MAP`.

### PR DESCRIPTION
**Pull request by XhmikosR**
TODO:

- [ ] Change content types for ttf, woff and woff2 to `font/type`?
- [ ] Adapt tests so that we don't test content-type twice: one for `content-type: undefined` and a second for each file type manually

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jmervine: I enabled mocha's full output.

As you can see, we have a lot of duplicate stuff in functional:

1. We need to remove `content-type: undefined` if we are going to check individually later
2. We don't need to run `assertItWorks both for each group test and in `public/**/*.*`
3. We probably should remove the custom code that stops testing `twitter-bootstrap` now that tests are fast
4. `content-type` in `public/**/*.*` is duplicate for most files since we do it individually too

I suggest that

1. we stop running functional explicitely for each group of files
2. change the `assertHeaders` some way so that the `content-type` is tested

Maybe I'm missing something, but I believe we could reduce the tests a lot. :)

**Comment by XhmikosR** [comment]
@jmervine: I think you missed my comments here and approved by just looking at the code :)

**Comment by jmervine** [comment]
You’re welcome to refactor as you see fit. I’ll review. Happy to take a stab but it won’t be in the next week to 10 days.

**Comment by XhmikosR** [comment]
No problem, I'll try to figure it out, otherwise I'll wait. I definitely think this is worth it because we duplicate many tests currently.

**Comment by XhmikosR** [comment]
I'm gonna merge this and make an issue for the other things.

**Pull request merged**
