### PR TITLE
Load Bootswatch from npm too.

### LINKED ISSUE #948: Change bootswatch.js script to use GitHub tags
Currently we get the files from the live server. This is bad, because we don't follow any version control. So if one runs `npm run bootswatch 3.3.7` you will see the files will differ.

We should retrieve the GitHub tag instead.

@jmervine: if you make any progress just ping me.

### PR DESCRIPTION
**Pull request by XhmikosR**
We might need to try another module since fs-extra doesn't seem to cover us here; exclude still copies all the files...

Any help is welcome.

Fixes #948.

### CODE REVIEW

**Comment by jmervine** [comment]
Might just be worth walking and only copying files that match the extensions we support.

**Comment by XhmikosR** [comment]
@jmervine: can you review again? Also, please try this branch too just to be safe.

**Comment by jmervine** [comment]
Resolved conflicts as well.

**Comment by XhmikosR** [comment]
@jmervine: we'll need to try your suggestion later. :)

**Pull request merged**
