### PR TITLE
Add Bootlint 0.16.2

### PR DESCRIPTION
**Pull request by XhmikosR**
@jmervine ping me when you upload the new files

### CODE REVIEW

**Comment by XhmikosR** [comment]
Updated, I messed up dist so I had to release 0.16.2.

**Comment by XhmikosR** [comment]
@jmervine: did you upload the new files?

**Comment by jmervine** [comment]
No. Give about 10 minutes.

**Comment by XhmikosR** [comment]
Oh, OK because you approved :P

**Pull request merged**
