### PR TITLE
Add About page

### LINKED ISSUE #1014: Add an About page
We discussed this with @jdorfman the other day on Slack.

I think we should have a simple About page, listing some of the core values, principles and history of the project.

### PR DESCRIPTION
**Pull request by jdorfman**
@XhmikosR @jmervine need you to both review before merging 

Fixes #1014.

- [x] Typos
- [x] Tests
- [x] Footer link
- [x] Tweak looks

### CODE REVIEW

**Comment by jdorfman** [comment]
Thank you. I hate jade/pug. I made some updates to the text. I will pull and push

**Comment by XhmikosR** [comment]
@jdorfman: make sure you don't overwrite my changes.

**Comment by jdorfman** [comment]
I keep getting merge conflicts can you please update about.pug with the following? I need to get to bed.

```jade
extends layout.pug

block content
    .row
        .col-12

            h2.text-center.mb-4 About

            p
                | BootstrapCDN was founded in 2012 by 
                a(href='https://twitter.com/DavidHenzel', target='_blank', rel='noopener') David Henzel
                |  and Justin Dorfman at MaxCDN. Today, BootstrapCDN is used by over 
                a(href='https://trends.builtwith.com/cdn/BootstrapCDN') 5.1 million sites
                |  delivering over 70 billion requests a month.

            p There are currently 3 maintainers:

            ul.list-unstyled
                each author in config.authors
                    li
                        a(href=author.url, rel='noopener', target='_blank')=author.name 

            h2.my-4 Core Values

            h3.h4
                strong 1. Security

            p.
                We agree with StackPath, security should be built in, not bolted on.
                Our DNS & CDN is managed by StackPath. Our origin server is S3.
                This website is hosted by Heroku. We enforce 2-factor authentication
                on all services (including GitHub, MarkMonitor, AWS & Gmail).
                Our master branch on GitHub is protected to disable force pushing,
                prevent branches from being deleted, and require status checks before merging.
                Our domain (*.bootstrapcdn.com) is managed by MarkMonitor, an ICANN-accredited
                registrar and recognized industry leader since 1999. They have security measures
                in place such as registry locking and IP restrictions to help reduce security
                vulnerabilities and minimize the likelihood of successful domain hijacking.
                By default we include Subresource Integrity (SRI) hashes when users copy a code
                snippet from this site.

            h3.h4
                strong 2. Reliability

            p
                | Reliable services require reliable people. StackPath's network is monitored 24/7/365 
                | and any incidents are posted to their 
                a(href='https://status.stackpath.com/') status page 
                | in real-time. Twitter is monitored for any mentions
                | of the terms "BootstrapCDN", "#BootstrapCDN", "Bootstrap CDN". There is someone
                | always on call and has direct access to the StackPath support team via a private
                | Slack channel. As mentioned above, we only use services that are secure & reliable.
                | Every Pull Request requires to pass a test that checks every file we deliver, making ~21K tests in total,
                | to make sure all of the HTTP headers are correct and SRI hashes match.

            h3.h4
                strong 3. Accessibility

            p
                | We must do everything we can to make sure this service is accessible to all.
                | We do that by providing IPv6 support, we are also whitelisted in 
                a(href='https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=bootstrapcdn&type=') Google AMP 
                | & the "Great Firewall of China".
                | Last but not least, we have Points of Presence (POPs) in North America, South America, Europe & Asia-Pacific region (
                a(href='https://www.stackpath.com/network/') view network map
                | ).

//- vim: ft=pug sw=4 sts=4 et:
```

**Comment by XhmikosR** [comment]
Sure thing, don't worry about it :)

**Comment by XhmikosR** [comment]
I think this is mostly ready.

Please verify and let me know if you want me to change something.

**Pull request merged**
