### PR TITLE
Checking js and css content types more exactly.

### PR DESCRIPTION
**Pull request by jmervine**
@jdorfman This will provide better testing for updated contents once #949 is complete.

### CODE REVIEW

**Comment by jmervine** [comment]
PS it will fail terribly before hand. =D

**Comment by jmervine** [comment]
Once the cdn is purged, kick off these Travis runs again and I believe they’ll pass. I’ll f they don’t I’ll check it out. Just let me know once they’ve run. 

This PR is tests only so it can be merged once passing.

**Comment by jdorfman** [comment]
@jmervine I want to wait for @petarpetrovic or someone on the StackPath side to monitor the logs right after I purge all just in case. Cool?

**Comment by XhmikosR** [comment]
I restarted Travis but tests still seem to fail.

**Comment by XhmikosR** [comment]
It seems that map files need to be re-uploaded with the new content type.

Anyway, after this is solved we can merge #971 .

**Comment by jmervine** [comment]
This has been run on `public/js` and `public/css` which was missing before. Additionally I reran it for all `map` files. 

@jdorfman The CDN needs a purge for `*.map` files as well as the two directories mentioned above.

**Comment by jdorfman** [comment]
@jmervine sorry just saw this =/

Purged and restarted the test

**Pull request merged**
