### PR TITLE
Replace themes.

### PR DESCRIPTION
**Pull request by zoltanszogyenyi**
Replaced two themes that were no longer available with newer ones from Themesberg.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jdorfman do we still need to keep the themes page?

**Comment by zoltanszogyenyi** [comment]
Just did that and they all got skipped.

**Comment by XhmikosR** [comment]
I definitely get some savings here.

**Comment by jdorfman** [comment]
@XhmikosR please merge this. We can evaluate the need for a themes page in the future. =)

**Comment by XhmikosR** [comment]
It will have to wait until tomorrow morning my time.

**Comment by zoltanszogyenyi** [comment]
@XhmikosR I optimized the images with setting the max variable to 80 and managed to save some more.

**Comment by XhmikosR** [comment]
Thanks but I'm not a fan of lossy optimization for jpeg. Especially in
images like these.

I will do it myself tomorrow.

**Comment by jdorfman** [comment]
Thanks @XhmikosR.

**Pull request merged**
