### PR TITLE
Add `sr-only` for "Toggle Dropdown" buttons

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@patrickhlauke: can you have a quick look please? Thanks!

**Comment by XhmikosR** [comment]
@patrickhlauke: friendly ping :) Also, maybe we could just use `aria-label` instead? Not sure what's better.

**Comment by patrickhlauke** [comment]
can't see anything on the preview, but working out what i assume the `.pug` things render to, it looks fine to me. `aria-label` is also an option, sure.

**Comment by XhmikosR** [comment]
@patrickhlauke is there any preferable way? The preview should be up now.

**Comment by patrickhlauke** [comment]
they're equivalent, as they lead to the same end result.

btw the "Old Versions" and "Resources" in the top navigation could also do with this addition.

**Comment by XhmikosR** [comment]
Thanks for the replies! I think `aria-label` is the "simplest", i.e. no need to add a new element. I'm gonna experiment with it first.

About "Old Versions" and "Resources" are you sure it's needed? I mean those have text in them.

**Comment by patrickhlauke** [comment]
> About "Old Versions" and "Resources" are you sure it's needed? I mean those have text in them.

ah, good point, i was probably being a bit overzealous. no you're right, they'll announce as "Old versions - collapsed" / "Old versions - expanded" ... which should be clear enough indication. yeah, forget that i mentioned them.

**Comment by XhmikosR** [comment]
@patrickhlauke can you check one last time please? I switched to `aria-label='Toggle Dropdown'`

**Comment by patrickhlauke** [comment]
LGTM

completely unrelated: maybe add `readonly` attribute to the text inputs? there's no point keeping them editable (and with readonly, they can still be focused/have the copy behavior)

**Comment by XhmikosR** [comment]
Thanks for confirming!

Feel free to make a PR, otherwise I'll make an issue to track this.

**Pull request merged**
