### PR TITLE
Merge Bootstrap 3 and 4 configs.

### LINKED ISSUE #964: Bootstrap 4.0.0 stable
I'm opening this issue to discuss how to proceed and track what do to.

TODO:

- [x] Adapt frontend to remove the Beta warning
- [x] Merge config for bootstrap 3 and 4
- [x] Adapt frontend to only show the latest version
- [x] Adapt tests for the above stuff

### PR DESCRIPTION
**Pull request by XhmikosR**
Also, make sure bootstrapcdn.json only includes versions below 4.

TODO:

- [x] Fix semver checks for versions like `3.0.0-noicons`

Fixes #964

### CODE REVIEW

**Comment by XhmikosR** [comment]
Justin, did you update the symlink? If so can you restart Travis ?

**Comment by XhmikosR** [comment]
Ping @jdorfman ^^

**Comment by jdorfman** [comment]
What needs to be done to close this PR?

**Comment by XhmikosR** [comment]
I need to resolve the conflicts when I have time.

**Comment by XhmikosR** [comment]
@jmervine: please review carefully. My initial patch was different, but current develop branch includes your `current` changes which I have basically reverted. I'm using semver instead like in my initial patch, but I haven't looked closely to your changes so we need to make sure we don't break something we don't want to.

**Comment by XhmikosR** [comment]
BTW the PR deployments seem to be broken @jmervine.

**Comment by XhmikosR** [comment]
@jmervine: friendly ping for a quick review. :)

**Comment by XhmikosR** [comment]
All right, I'll try to adapt the changes for current in tests.

**Pull request merged**
