### PR TITLE
Production release

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by jdorfman** [comment]
@jmervine it isn't updating (for me)

**Comment by jdorfman** [comment]
@XhmikosR we also need to update quick start to `4.1.2`

image

**Comment by jdorfman** [comment]
I see you did it, but it isn't updating on Heroku. @jmervine any ideas?

**Comment by XhmikosR** [comment]
This isn't done manually. If the website is updated properly everything
else will be ok.

I'm afk until tomorrow my time BTW.

On Jul 12, 2018 23:31, "Justin Dorfman" <notifications@github.com> wrote:

@XhmikosR <https://github.com/XhmikosR> we also need to update quick start
to 4.1.2

[image: image]
<https://user-images.githubusercontent.com/398230/42657707-ec97f2f0-85d7-11e8-8109-3529ac56b65d.png>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/MaxCDN/bootstrapcdn/pull/1189#issuecomment-404641130>,
or mute the thread

**Pull request merged**
