### PR TITLE
Add bootstrap v4.4.0

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jmervine ping me when it's live

**Comment by jdorfman** [comment]
@XhmikosR files are live, having some issues with the headers. @jmervine we should document this process so all three of us can do it going forward. =)

**Comment by XhmikosR** [comment]
@jmervine can you fix the content types please?

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
