### PR TITLE
Add Bootswatch v4.0.0.

### LINKED ISSUE #968: Bootswatch 4.0.0
I'll take a stab at it later today or tomorrow. After that, @jdorfman you will need to update the CDN; better wait until I commit the files so that we don't have broken SRI hashes.

/CC @m5o FYI

### PR DESCRIPTION
**Pull request by XhmikosR**
@jdorfman: please upload the files on the CDN and make sure the `latest` symlink works fine.

Fixes #968

### CODE REVIEW

**Comment by jdorfman** [comment]
Uploaded. I _think_ going forward we should stop updating `/latest` since it is bad practice.  Thoughts?

**Comment by XhmikosR** [comment]
The `latest` feature is pretty useful IMO. How many people use it?

**Comment by jdorfman** [comment]
@XhmikosR if you find it useful then we will keep it. I'll check the stats.

**Comment by XhmikosR** [comment]
@jdorfman: we need the symlink updated otherwise tests fail.

**Comment by jdorfman** [comment]
@XhmikosR ok sorry. Also `latest` will stay

cloudapp annotation 2018-01-22 at 7 49 17 am png

**Comment by XhmikosR** [comment]
Yeah, that is why I said I find it useful. ;)

**Comment by jdorfman** [comment]
@jmervine wasn't the pseudo symlink was fixed in the test?

**Comment by XhmikosR** [comment]
All right, I'll revert the `latest` update here and in the other PR tomorrow, so don't merge yet.

**Comment by XhmikosR** [comment]
@jdorfman: please make sure you revert the symlink update on the CDN.

**Comment by XhmikosR** [comment]
I don't get why tests are failing, but unless they pass, I'm forced to not merge...

**Comment by jmervine** [comment]
The tests are failing because the five files mention in the test output are missing from S3. I confirmed this.

Keep in mind, S3 doesn't support symlinks, so files need to be manually copied in to those locations.

**Comment by XhmikosR** [comment]
I reverted the symlink updates after discussing it with @jdorfman. And we came to the decision that we shouldn't update them, and eventually drop them because they are very dangerous the way we use them (no version control in the URL, so things *will* break going from v3 to v4, etc.).

**Comment by jdorfman** [comment]
@XhmikosR looks like the tests need to updated

**no longer supported:**
- **Paper:** https://maxcdn.bootstrapcdn.com/bootswatch/latest/paper/bootstrap.css
- **Readable:** https://maxcdn.bootstrapcdn.com/bootswatch/latest/readable/bootstrap.css
- **Bootstrap Theme:** https://maxcdn.bootstrapcdn.com/twitter-bootstrap/latest/css/bootstrap-theme.css
- https://maxcdn.bootstrapcdn.com/twitter-bootstrap/latest/js/npm.js

**Comment by XhmikosR** [comment]
What do you mean no longer supported?

**Comment by XhmikosR** [comment]
Also, did you revert the symlink stuff to v3.3.7 on the CDN?

**Comment by jmervine** [comment]
@XhmikosR RE
> Also, did you revert the symlink stuff to v3.3.7 on the CDN?

The "CDN", which is really the origin, or S3, doesn't support symlinking. So things have to be mirrored.

**Comment by XhmikosR** [comment]
Yeah, that is what I meant :P

**Comment by jdorfman** [comment]
@XhmikosR @jmervine for this to test to pass the following 5 URL's need to be removed:

```
5 failing
  1) functional
       public/**/*.*
         https://maxcdn.bootstrapcdn.com/bootswatch/latest/paper/bootstrap.css
           content-type:
      Uncaught AssertionError [ERR_ASSERTION]: file missing or forbidden
      + expected - actual
      -200
      +403
      
      at request (tests/functional_test.js:265:32)
      at helpers.preFetch (tests/functional_test.js:55:9)
      at IncomingMessage.res.on (tests/test_helper.js:134:29)
      at endReadableNT (_stream_readable.js:1055:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  2) functional
       public/**/*.*
         https://maxcdn.bootstrapcdn.com/bootswatch/latest/readable/bootstrap.css
           content-type:
      Uncaught AssertionError [ERR_ASSERTION]: file missing or forbidden
      + expected - actual
      -200
      +403
      
      at request (tests/functional_test.js:265:32)
      at helpers.preFetch (tests/functional_test.js:55:9)
      at IncomingMessage.res.on (tests/test_helper.js:134:29)
      at endReadableNT (_stream_readable.js:1055:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  3) functional
       public/**/*.*
         https://maxcdn.bootstrapcdn.com/twitter-bootstrap/latest/css/bootstrap-theme.css
           content-type:
      Uncaught AssertionError [ERR_ASSERTION]: file missing or forbidden
      + expected - actual
      -200
      +403
      
      at request (tests/functional_test.js:265:32)
      at helpers.preFetch (tests/functional_test.js:55:9)
      at IncomingMessage.res.on (tests/test_helper.js:134:29)
      at endReadableNT (_stream_readable.js:1055:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  4) functional
       public/**/*.*
         https://maxcdn.bootstrapcdn.com/twitter-bootstrap/latest/css/bootstrap-theme.min.css
           content-type:
      Uncaught AssertionError [ERR_ASSERTION]: file missing or forbidden
      + expected - actual
      -200
      +403
      
      at request (tests/functional_test.js:265:32)
      at helpers.preFetch (tests/functional_test.js:55:9)
      at IncomingMessage.res.on (tests/test_helper.js:134:29)
      at endReadableNT (_stream_readable.js:1055:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  5) functional
       public/**/*.*
         https://maxcdn.bootstrapcdn.com/twitter-bootstrap/latest/js/npm.js
           content-type:
      Uncaught AssertionError [ERR_ASSERTION]: file missing or forbidden
      + expected - actual
      -200
      +403
```

**Comment by XhmikosR** [comment]
The files do exist. I don't see why you say that.

**Comment by XhmikosR** [comment]
The bootstrap file are unrelated; we don't touch them here. So clearly something else got messed up.

Please make sure you have all files in sync on S3.

**Comment by jmervine** [comment]
The following sub-set of specs 
```
  4) functional
       public/**/*.*
```
checks everything in the public directory checked in to github against the CDN. So if these are failing, then they exist in the version symlinked to latest, the just weren't copied to latest directory in S3. TL;DR the repo and S3 are out of sync.

**Comment by jdorfman** [comment]
@XhmikosR @jmervine let's start with the Bootswatch errors, please go to https://bootswatch.com/ 

now search for the following themes: `paper`, `readable`

Am I missing something?

**Comment by XhmikosR** [comment]
@jdorfman: we don't have them for v4 either.

**Comment by jmervine** [comment]
I'll try to look closer at this this afternoon. I've been traveling and really only looking on my phone. My guess is the symlink is point to the wrong directory, or the latest directory has the old files. Probably the former.

**Comment by XhmikosR** [comment]
Note, guys, that you shouldn't hurry to release this because it's not being used yet in the frontend.

I'll fix that later or tomorrow after tests pass.

**Comment by XhmikosR** [comment]
Any news guys?

**Comment by jmervine** [comment]
RE latest and the stats you posted. While 40K seems like a lot, it’s 0.003%. Killing latest is a good idea. It’s useful for testing but will it’s bad practice to use it in the real world.

**Comment by jmervine** [comment]
Also it’s been removed on develop — https://github.com/MaxCDN/bootstrapcdn/pull/979, so this branch needs a rebase.

**Pull request merged**
