### PR TITLE
Add Bootlint, Bootswatch 3 and Bootswatch 4 in bootstrapcdn.json.

### LINKED ISSUE #1281: JSON API missing bootswatch & bootlint
Hello again 😄

I originally opened #460 a while back and from that, y'all ended up creating:

https://www.bootstrapcdn.com/data/bootstrapcdn.json

This has been fantastic but given the recent changes/overhaul I've been doing in https://www.drupal.org/project/bootstrap/issues/3031415, I'm realizing this data is rather incomplete.

It doesn't contain any of the other package data that this CDN provides (e.g. bootswatch, bootlint).

I see that this JSON file is dynamically generated here:
https://github.com/MaxCDN/bootstrapcdn/blob/develop/lib/helpers.js#L37-L60

### LINKED ISSUE #1283: Revisit JSON entries
1. We don't list Bootstrap >= 4. Maybe we should revisit this? Not sure how breaking it can be
2. Add SRI hashes. This unfortunately will change the output format for Font Awesome, Bootlint and Bootswatch because we need a key for each one. So if we are going to go this way, better do it in #1282 

/CC @jdorfman @jmervine for thoughts

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #1281, fixes #1283

### CODE REVIEW

**Comment by XhmikosR** [comment]
The thing is that if we are going to add SRI hashes too, this should be done here so that we introduce potentially breaking changes once. See #1283

**Comment by markcarver** [comment]
The `bootswatch3` and `bootswatch4` packages only provide the latest `4.3.1` and `3.4.1` versions respectively. This would need to provide all the versions in the API; like the other packages currently do.

**Comment by XhmikosR** [comment]
Because that's the only thing we expose. I don't plan to change this personally.

**Comment by markcarver** [comment]
Also the new data is using new `uri` and `sri` properties, which is different from the existing `bootstrap` package.

These need to be consistent for any sort of API integration to be functional.

I get the frustration and worry of potentially breaking the existing API.

Perhaps this should just be a new dynamically generated route/endpoint?

> Because that's the only thing we expose. I don't plan to change this personally.

Well, Drupal Bootstrap's UI has to match versions between Bootstrap and Bootswatch. If the API doesn't return all available versions, it has to assume that it doesn't exist, which is the case for some versions in other CDNs.

You don't have to expose this on the front facing site, but as far as the API goes, we need to know which versions are available for this to be even remotely functional.

**Comment by markcarver** [comment]
> Perhaps this should just be a new dynamically generated route/endpoint?

A simple listing, like a `files` array for each "package", where each file is its own object. Simlar to https://data.jsdelivr.com/v1/package/npm/bootswatch@3.4.0/flat would be extremely helpful.

Not sure how the routes work in this, but maybe even make the "package" part of the URL so only the necessary package data is returned?

Not trying to make things difficult, just thinking out loud and trying to help come up with ideas.

**Comment by XhmikosR** [comment]
You can always provide a patch if you want assuming it doesn't break the `scripts/` because those are not tested on CI.

I'm open to any patch as long as it works properly. I just don't have the time to do this.

So, my suggestion is to first merge this, and then someone else works on providing the extra stuff.

**Comment by markcarver** [comment]
Still don't understand why you're pursing this over #1284...

**Comment by XhmikosR** [comment]
I'm not pursuing anything, I just rebased the branch. I don't have the time to review nor maintain #1284.

**Comment by markcarver** [comment]
Clearly...

**Comment by markcarver** [comment]
FTR, you were never open to the idea of it and didn't even give it a chance. Now, https://www.drupal.org/project/bootstrap/issues/3053525 can never happen.

**Comment by XhmikosR** [comment]
It's a matter of time. I don't have the time to maintain such a change.

**Comment by markcarver** [comment]
If you say so. From my perspective, it's more of a matter of pride, arrogance and your unwillingness to accept help (or ideas) from others. I created that entire API and offered to help maintain it (over a year ago); you didn't do a damn thing.

This isn't the first time either. I've tried supporting and integrating this project (and jsDelivr) for https://www.drupal.org/project/bootstrap for several years now. All I seem to get through is attitude, dismissiveness and quite frankly a complete lack of interest in providing quality code and features for genuine needs/use-cases. Nevermind the constant lack of stability with the "API".

I know I'm being aggressive, but I'm genuinely angry and disheartened by the lack of "community" FOSS projects like this actually are over what they "claim" to be. People will see the words I use here and say I'm the "aggressor", but they rarely see the bigger picture of the **actions or inactions** taken by those that **instigate** said responses in the first place.

If you want to maintain proprietary software, then don't put it on GH.

I'm done trying to contribute to this project or jsDelivr; y'all are clearly going to do whatever you want.

**Comment by XhmikosR** [comment]
You are totally out of line.

**Comment by markcarver** [comment]
> You are totally out of line.

See. Immediate dismissal. You clearly didn't even read what I wrote. That's the entire point I was attempting to make.

**Comment by XhmikosR** [comment]
Because your attitude is bad. I don't own you nor anyone else shit for what I do in my spare time.

Take your toxicity elsewhere.

**Comment by markcarver** [comment]
> Because your attitude is bad.

No. My attitude is a direct correlation to your dismissiveness, responses, actions, and inactions. You instigated this. You always have. You have never taken any responsibility for discourse. I already stated and owned the fact that my attitude was angry. I can be angry, that's a valid emotion. One precipitated by said direct correlation.

> I don't own you nor anyone else shit for what I do in my spare time.

No. You don't. But guess what? You're not the only one doing stuff like this in their "spare time". All that work I did: spare time. It's called respect, of which you have none for others, but you certainly expect others to treat you with it. That's not how respect works. Also, I have never used profanity with you... so thanks for that.

> Take your toxicity elsewhere.

Stating facts isn't "toxicity". I'm simply sharing my **interaction experience with you over many years** so that others can see how you treat people and hopefully so you can see how you treat people. This is a public space and your interactions with me over the years have been egregiously dismissive and insulting.

That all being said, this will be my last response, so you don't have to worry about my supposed "toxicity" any longer.

I hope you have a better day and stay safe; just please work on your attitude and acceptance of others. I would hate for anyone else to feel this way when working on this project with you.

**Comment by XhmikosR** [comment]
@jmervine @jdorfman feel free to deal with Mark. I'm gonna take the time to fix my attitude because clearly I started this thing out of nowhere.

**Pull request closed without merging**
