### PR TITLE
Revert "Move JS outside of HTML and preprocess it."

### PR DESCRIPTION
**Pull request by XhmikosR**
Reverts MaxCDN/bootstrapcdn#973

### CODE REVIEW

**Comment by jdorfman** [comment]
@jmervine any chance you can look into the `continuous-integration/travis-ci/pr` failure?

**Comment by jmervine** [comment]
A hand full of files timed out when loading off the cdn. Restarted the test run.

**Comment by jdorfman** [comment]
@XhmikosR @jmervine merge when ready

**Comment by XhmikosR** [comment]
>This pull request can be automatically merged by project collaborators
Only those with write access to this repository can merge pull requests.

**Pull request merged**
